directories:
  output: release
  buildResources: build
appId: com.prinit.desktop
productName: PrinIT
files:
  - filter:
      - dist
      - electron.cjs
win:
  target:
    - portable
portable:
  artifactName: PrinIT-${version}-portable.exe
electronVersion: 37.0.0
